<?php $quote_id=$block->getRequest()->getParam('quote_id');
$quote_helper = $this->helper('Magebees\QuotationManagerPro\Helper\Quotation');
$version=$quote_helper->getMagentoVersion();
$file_upload_config=$quote_helper->getFileUploadConfig();
$allow_file_upload=$file_upload_config['enable_file_upload'];?>

<form method="post" id="messageform" name="messageform" enctype="multipart/form-data" action="<?= $block->getUrl('quotation/quote/saveMessage')?>">
	<fieldset>
		<?= $block->getBlockHtml('formkey') ?>
		<input type="hidden" name="quote_id" value="<?= $quote_id?>">
		<textarea id="message" name="editor_text"></textarea>
		<p><input onclick="this.value = this.checked ? 1 : 0;" value="" name="is_notify_customer" id="is_notify_customer" type="checkbox"><?= /* @escapeNotVerified */ __('Notify Customer by Email') ?></p>
		
		<?php if($allow_file_upload):?>
			<h4><?= /* @escapeNotVerified */ __('Attach Files') ?></h4>
			<input id="file_path" name="upload_file[]" multiple="" type="file">
		<?php endif; ?>
		<p>&nbsp;</p>
		<div><button id="send_msg" type="submit" class="action primary"><?= /* @escapeNotVerified */ __('Send Message') ?></button></div>
	</fieldset>
</form>

 <?php if(version_compare($version, '2.3.0', '<')): ?>
<script>
require([
        'jquery',
        'mage/adminhtml/wysiwyg/tiny_mce/setup'
    ], function(jQuery){

    var config = {}, 
        editor;

    jQuery.extend(config, {
        settings: {
            theme_advanced_buttons1 : 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
                                        'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
            theme_advanced_buttons2: null,
            theme_advanced_buttons3: null,
            theme_advanced_buttons4: null,
            theme_advanced_statusbar_location: null
        },
        files_browser_window_url: false
    });
    editor = new tinyMceWysiwygSetup(
        'message',
        config
    );
    editor.turnOn();
    jQuery('#message')
        .addClass('wysiwyg-editor')
        .data(
            'wysiwygEditor',
            editor
        );
});
</script>
<?php else:?>
<script>
    require([
    "jquery", 
    "mage/translate", 
    "mage/adminhtml/events", 
    "mage/adminhtml/wysiwyg/tiny_mce/setup"
    ], function(jQuery){
        wysiwygEditor = new wysiwygSetup("message", {
            "width":"99%",  // defined width of editor
            "height":"200px", // height of editor
            "plugins":[{"name":"image"}], // for image
            "tinymce4":{"toolbar":"formatselect | bold italic underline | alignleft aligncenter alignright | bullist numlist | link table charmap","plugins":"advlist autolink lists link charmap media noneditable table contextmenu paste code help table",
            }
        });
        wysiwygEditor.setup("exact");
    });
</script>
<?php endif; ?>