<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php if($block->getCustomerId()==0): ?>
<div class="admin__page-section-title <?= /* @escapeNotVerified */ $block->getAccountHeaderCssClass() ?>">
    <span class="title"><?= /* @escapeNotVerified */ $block->getAccountHeaderText() ?></span>
    <div class="actions"></div>
</div>
<div id="customer_account_fieds" class="admin__page-section-content">
    <?= $block->getForm()->getHtml() ?>
</div>
<?php endif; ?>
<script>
    require(["prototype", "Magebees_QuotationManagerPro/quote/view/form"], function(){
        quote.accountFieldsBind($('customer_account_fieds'));
    });
</script>
