<?php
$quote_helper = $this->helper('Magebees\QuotationManagerPro\Helper\Quotation');
$version=$quote_helper->getMagentoVersion();
if(version_compare($version, '2.2.0', '<'))
{
	$escaper=$this->helper(\Magento\Framework\EscapeHelper::class);
}
else
{
	$escaper=$block;
}
?>
<div class="block block-customer-login" id="popup-modal-login" style="display:none">
    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Registered Customers')) ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"              
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
				  <div class="messages">
                <div class="message message-error error">
                    <div></div>
                </div>
</div>
                <div class="field note"><?= $block->escapeHtml(__('If you have an account, sign in with your email address.')) ?></div>
                <div class="field email required">
                    <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input name="login[username]" value="<?= $escaper->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>" data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control">
                        <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?= $escaper->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar">
                    <div class="primary"><button  class="quote-action-login primary" name="send" id="send2"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button></div>
                    <div class="secondary"><a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a></div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
<style>
	  #popup-modal-login .form-login .messages .message {
            display: none;
        }
    </style>
<script>
require(['jquery','Magento_Ui/js/modal/modal','mage/mage'],
function($, modal) {
var options = {
type: 'popup',
responsive: true,
innerScroll: true,
modalClass: 'custom-block-customer-login',
buttons: false,
};

$('#login-popup').click(function(){
var popup = modal(options, $('#popup-modal-login'));
$('#popup-modal-login').modal('openModal');
});
	
	
       
            var dataForm = $('.form-login');
            dataForm.mage('validation', {});
          
           
            $('.quote-action-login').on('click',function () {			
                if(dataForm.validation('isValid')){				
					var params=$('.form-login').serialize();
					   var url='<?php echo $quote_helper->getAjaxLoginUrl(); ?>';
                    $.ajax({
                       
                        url:url,
                     	method:'POST',
						dataType:"json",
						showLoader:true,
						data: params,
                        success: function (response) {
                           
                            if (!response.errors) {
                                location.reload();
                            } else {
                                $('#popup-modal-login .form-login .messages .message div').text(response.message);
                                $('#popup-modal-login .form-login .messages .message').show();
                                setTimeout(function() {
                                    $('#popup-modal-login .form-login .messages .message').hide();
                                }, 5000);
                            }
                        }
                    });
                    return false;
                }
            });	
});
	</script>