<?php
/**
 * Stores switcher template
 * <?php echo $block->escapeHtml($_lang['code']); ?>
 */
$countries = $block->getCountriesForAllStores();
?>
<?php if ($countries>1): ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>    
<div class="switcher shipping switcher-shipping" data-ui-id="shipping-switcher" id="switcher-shipping<?php /* @escapeNotVerified */ echo $id?>">
    <span class="label switcher-label"><?php echo __('Shipping') ?></span>
    <div class="actions options switcher-options">
        <div class="action toggle switcher-trigger" id="switcher-shipping-trigger<?php /* @escapeNotVerified */ echo $id?>">
            <strong class="change view-<?php echo $block->escapeHtml($block->getCurrentShippingCode()) ?>">
                <img alt="<?php echo $block->getCurrentShippingCountry() ?>"
                     src="<?= $block->getViewFileUrl('images/flags/4x3/' . strtolower($block->escapeHtml($block->getCurrentShippingCode())) . '.png') ?>"/></span>
                <span class="material-icons">arrow_drop_down</span>
            </strong>
        </div>
        <ul class="dropdown switcher-dropdown shipping-dropdown" data-mage-init='{"dropdownDialog":{
                    "appendTo":"#switcher-shipping<?php /* @escapeNotVerified */ echo $id?> > .options",
                    "triggerTarget":"#switcher-shipping-trigger<?php /* @escapeNotVerified */ echo $id?>",
                    "closeOnMouseLeave": false,
                    "triggerClass":"active",
                    "parentClass":"active",
                    "buttons":null}}'>
                <?php foreach ($countries as $_lang): ?>
                        <li class="view-<?php echo $block->escapeHtml($_lang['code']); ?> switcher-option">
                            <a href="#" data-post='<?php /* @escapeNotVerified */ echo $_lang['url']; ?>' >
                                <img alt="<?php echo $block->escapeHtml($_lang['label']) ?>"
                                     src="<?= $block->getViewFileUrl('images/flags/4x3/' . strtolower($block->escapeHtml($_lang['code'])) . '.png') ?>"/>
                                <span><?php echo $block->escapeHtml($_lang['label']) ?></span>
                            </a>
                        </li>
                <?php endforeach; ?>
        </ul>
    </div>
</div>
<script>
    require([
        "jquery",
        "mage/cookies"
    ], function(jQuery){
        (function($) {
            $(document).on('click', '#switcher-shipping a[data-post]', function() {
                var postData = $(this).data('post');
                $.cookie('ssc_h_dd', postData.data.ssc_h_dd, { path: '/' });
            })
        })(jQuery);
    });
</script>
<?php endif; ?>

