<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * Currency switcher
 *
 * @var \Magento\Directory\Block\Currency $block
 */

?>
<?php if ($block->getCurrencyCount() > 1): ?>
<?php $currencies = $block->getCurrencies(); ?>
    <?php $currentCurrencyCode = $block->getCurrentCurrencyCode(); ?>
    <?php


    function getCurencySymbol($code) {
        $_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $currency = $_objectManager->create('Magento\Directory\Model\CurrencyFactory')->create()->load($code);
        $currencySymbol = $currency->getCurrencySymbol();
        return $currencySymbol;
    }
    ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>

<div class="switcher currency switcher-currency" data-ui-id="currency-switcher" id="switcher-currency<?php /* @escapeNotVerified */ echo $id?>">
    <span class="label switcher-label"><?php echo __('Price in') ?></span>
    <div class="actions options switcher-options">
        <div class="action toggle switcher-trigger" id="switcher-currency-trigger<?= $block->escapeHtmlAttr($id) ?>">
            <strong class="change view-<?php echo $block->escapeHtml($block->getCurrentCurrencyCode()) ?>">
                <span id="current-store-cookie-currency"><span><?= getCurencySymbol($block->escapeHtml($currentCurrencyCode)) ?></span></span>
                <span class="material-icons">arrow_drop_down</span>
            </strong>
        </div>
        <ul class="dropdown switcher-dropdown currency-dropdown" data-mage-init='{"dropdownDialog":{
                "appendTo":"#switcher-currency<?php /* @escapeNotVerified */ echo $id?> > .options",
                "triggerTarget":"#switcher-currency-trigger<?php /* @escapeNotVerified */ echo $id?>",
                "closeOnMouseLeave": false,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":null}}'>
            <?php foreach ($currencies as $_code => $_name): ?>
                <?php if ($_code != $currentCurrencyCode): ?>
                    <li class="view-<?= $block->escapeHtmlAttr($_code) ?> switcher-option">
                        <a href="#" data-post='<?= /* @noEscape */ $block->getSwitchCurrencyPostData($_code) ?>'>
                            <span><?= getCurencySymbol($block->escapeHtml($_code)) ?></span>
                            <span><?= $block->escapeHtml($_code) ?></span>
                        </a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
    
<?php endif; ?>
