<?php
/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); 
$check_addtocart=false;
$quote_helper = $this->helper('Magebees\QuotationManagerPro\Helper\Quotation');
$is_enable_groupwise=$quote_helper->isEnableCustomerGroupWise();
$config=$quote_helper->getConfig();
$frontend_config=$quote_helper->getFrontendConfig();
$hideprice_config=$quote_helper->getHidePriceConfig();
$enable_addtocart=$frontend_config['enable_qaddtocart'];
$enable_price=$quote_helper->isEnablePriceCustGroupWise($_product);
$enable_manage_stock=$frontend_config['enable_manage_stock'];
$stockwise_quote=$quote_helper->isEnableStockWise($_product);
$attributewise_quote=$quote_helper->isEnableAttributeWise($_product);

?>
<?php $cartButtonTitle = __('Add to Cart'); ?>
<?php $quoteButtonTitle = __('Add to Quote'); ?>
<?php $validators = $block->escapeHtml(json_encode($block->getQuantityValidators())); ?>


    <div class="box-tocart">
        <fieldset class="fieldset">

            <?php if ($block->shouldRenderQuantity()) : ?>
                <!-- Qty start -->
                <div class="field qty">
                    <label class="label" for="qty"><span><?php echo __('Qty') ?></span></label>

                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               maxlength="12"
                               value="<?php echo $block->getProductDefaultQty() * 1 ?>"
                               title="<?php echo __('Qty') ?>" class="input-text qty"
                               data-validate="<?php echo $validators ?>"
                        />
                    </div>
                </div>
                <!-- Qty stop -->
            <?php endif; ?>

            <div class="actions">
				
				  <?php if($config['enable']): ?>				
				 <?php if($frontend_config['enable_btn_product']): ?>
				<?php if(($attributewise_quote=='Yes')&&($is_enable_groupwise)&&($stockwise_quote)):
				$check_addtocart=true;
$enable_price=$quote_helper->isEnablePriceCustGroupWise($_product);?>
				 <?php if(!$enable_price): ?>
				<script type="text/javascript">
	 require([
		  'jquery',
		  'domReady!'
	  ], function ($) {
		  $(document).ready(function () {		  
			  $('#product-options-wrapper .price-notice').remove();
			//  $('#product-options-wrapper .price-container').remove();
		  });
	   });
					</script>
				  <?php endif; ?>
						<!-- Quote button start -->
						<button type="submit"
								title="<?php echo $quoteButtonTitle ?>"
								class="action toquote"
								id="magebees-addtoquote-button">
							<span><?php echo $quoteButtonTitle ?></span>
						</button>
						<!-- Quote button stop -->
			  
			   <?php endif; ?>
			   <?php endif; ?>
		   <br/>
		   <br/>
				
				<?php if($check_addtocart)
				{				
					$is_show_addtocart=$enable_addtocart;
					if($is_show_addtocart)
					{
						if($enable_price)
						{
							$is_show_addtocart=$enable_addtocart;
						}
						else
						{
							$is_show_addtocart=false;
						}
					}			
				}
				else
				{
					$is_show_addtocart=true;
				}?>
                <?php if ($_product->isSaleable()) : ?>
				<?php if($is_show_addtocart):?>
				
                    <!-- Cart button start -->
                    <button type="submit"
                            title="<?php echo $cartButtonTitle ?>"
                            class="action primary tocart"
                            id="product-addtocart-button">
                        <span><?php echo $cartButtonTitle ?></span>
                    </button>
                    <!-- Cart button stop -->
                <?php endif; ?>
                <?php endif; ?>

           <?php endif; ?>

                <?php echo $block->getChildHtml('', true) ?>
            </div>
        </fieldset>
    </div>

<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script>
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/product/view/validation',
            'Magebees_QuotationManagerPro/js/catalog-add-to-cart'
        ], function ($) {
            'use strict';
            var addToQuote = false;
            $('#magebees-addtoquote-button').click(function (e) {
                addToQuote = "<?php echo $block->getUrl('quotation/quote/add')?>";
            });

            $('#product_addtocart_form').mage('validation', {
                radioCheckboxClosest: '.nested',
                submitHandler: function (form) {
                    var widget = $(form).magebeesQuoteToCart({
                        quoteFormUrl: addToQuote,
                        bindSubmit: false,
                        noAjax: false
                    });

                    widget.magebeesQuoteToCart('submitForm', $(form));
                    addToQuote = false;
                    return false;
                }
            });
        });
    </script>
<?php else : ?>
    <script>
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/product/view/validation',
            'Magebees_QuotationManagerPro/js/catalog-add-to-cart'
        ], function ($) {
            'use strict';
            var addToQuote = false;
            $('#magebees-addtoquote-button').click(function (e) {
                addToQuote = "<?php echo $block->getUrl('quotation/quote/add') ?>";
            });

            $('#product_addtocart_form').mage('validation', {
                radioCheckboxClosest: '.nested',
                submitHandler: function (form) {
                    var widget = $(form).magebeesQuoteToCart({
                        quoteFormUrl: addToQuote,
                        bindSubmit: false
                    });

                    widget.magebeesQuoteToCart('submitForm', $(form));
                    addToQuote = false;
                    return false;
                }
            });
        });
    </script>
<?php endif; ?>


