<?php $directoryHelper = $this->helper('Magento\Directory\Helper\Data');	
$quote_helper = $this->helper('Magebees\QuotationManagerPro\Helper\Quotation');	
$version=$quote_helper->getMagentoVersion();
if(version_compare($version, '2.2.0', '<'))
{
	$escaper=$this->helper(\Magento\Framework\EscapeHelper::class);
}
else
{
	$escaper=$block;
}
$login_customer=$quote_helper->getLoggedInCustomer();
$login_customer_data=$login_customer->getData();
$save_address_url=$quote_helper->getSaveAddressUrl();
$defaultCountryId = $directoryHelper->getDefaultCountry();
?>
<div class="block block-customer-address" id="popup-modal-address" style="display:none">
<form class="form-address-edit"
      action="<?= $block->escapeUrl($save_address_url) ?>"
      method="post"
      id="form-validate-quote-add-popup"
      enctype="multipart/form-data"
      data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>">
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Address')) ?></span></legend><br>
        <?= $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>">
        <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>">
        <input type="hidden" name="add_type" id="quote_add_type" value="">
        <?//= $block->getNameBlockHtml() ?>    
		  <div class="field field-name-firstname required">
            <label class="label" for="firstname">
                <span>First Name</span>
            </label>

            <div class="control">
                <input type="text" id="edit_firstname" name="firstname" value="<?php if(isset($login_customer_data['firstname'])){ echo $login_customer_data['firstname'];} ?>" title="First Name" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
            </div>
        </div>
			
			<div class="field field-name-lastname required">
            <label class="label" for="lastname">
                <span>Last Name</span>
            </label>

            <div class="control">
                <input type="text" id="edit_lastname" name="lastname" value="<?php if(isset($login_customer_data['lastname'])){ echo $login_customer_data['lastname'];} ?>" title="Last Name" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
            </div>
        </div>	
		<div class="field field-name-telephone required">
            <label class="label" for="telephone">
                <span>Telephone</span>
            </label>
		<div class="control">
                    <input type="text" name="telephone" id="edit_telephone" value="<?php echo $escaper->escapeHtmlAttr($block->getFormData()->getTelephone()) ?>" title="<?php echo $escaper->escapeHtmlAttr(__('Phone Number')) ?>" class="input-text <?php echo $escaper->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('telephone')) ?>">
                </div>
			</div>
        <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>
        <div class="field street required">
            <label for="street_1" class="label">
                <span><?= $block->escapeHtml(__('Street Address')) ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="street[]"
                       value="<?= $escaper->escapeHtmlAttr($block->getStreetLine(1)) ?>"
                       title="<?= $escaper->escapeHtmlAttr(__('Street Address')) ?>"
                       id="street_1"
                       class="input-text <?= $escaper->escapeHtmlAttr($_streetValidationClass) ?>"/>
                <div class="nested">
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 1, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i < $_n; $_i++): ?>
                        <div class="field additional">
                            <label class="label" for="street_<?= /* @noEscape */ $_i + 1 ?>">
                                <span><?= $block->escapeHtml(__('Street Address %1', $_i + 1)) ?></span>
                            </label>
                            <div class="control">
                                <input type="text" name="street[]"
                                       value="<?= $escaper->escapeHtmlAttr($block->getStreetLine($_i + 1)) ?>"
                                       title="<?= $escaper->escapeHtmlAttr(__('Street Address %1', $_i + 1)) ?>"
                                       id="street_<?= /* @noEscape */ $_i + 1 ?>_ship"
                                       class="input-text <?= $escaper->escapeHtmlAttr($_streetValidationClass) ?>">
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>

        <?php //if ($this->helper('Magento\Customer\Helper\Address')->isVatAttributeVisible()) : ?>
            <!--<div class="field taxvat">
                <label class="label" for="vat_id">
                    <span><?//= $block->escapeHtml(__('VAT Number')) ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="vat_id"
                           value="<?//= $escaper->escapeHtmlAttr($block->getAddress()->getVatId()) ?>"
                           title="<?//= $escaper->escapeHtmlAttr(__('VAT Number')) ?>"
                           class="input-text <?//= $escaper->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('vat_id')) ?>"
                           id="vat_id">
                </div>
            </div>-->
        <?php //endif; ?>
        <div class="field city required">
            <label class="label" for="city"><span><?= $block->escapeHtml(__('City')) ?></span></label>
            <div class="control">
                <input type="text"
                       name="city"
                       value="<?= $escaper->escapeHtmlAttr($block->getFormData()->getCity()) ?>"
                       title="<?= $escaper->escapeHtmlAttr(__('City')) ?>"
                       class="input-text <?= $escaper->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city')) ?>"
                       id="edit_city">
            </div>
        </div>
        <div class="field region required">
            <label class="label" for="region_id">
                <span><?= $block->escapeHtml(__('State/Province')) ?></span>
            </label>
            <div class="control">
                <select id="region_id_add" name="region_id_add"
                        title="<?= $escaper->escapeHtmlAttr(__('State/Province')) ?>"
                        class="validate-select" <?= /* @noEscape */ !$block->getConfig('general/region/display_all') ? ' disabled="disabled"' : '' ?>>
                    <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                </select>
                <input type="text"
                       id="region_add"
                       name="region_add"
                       value="<?= $escaper->escapeHtmlAttr($block->getRegion()) ?>"
                       title="<?= $escaper->escapeHtmlAttr(__('State/Province')) ?>"
                       class="input-text required-entry mage-error <?= $escaper->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region')) ?>"<?= !$block->getConfig('general/region/display_all') ? ' disabled="disabled"' : '' ?>/>
            </div>
        </div>
        <div class="field zip required">
            <label class="label" for="zip">
                <span><?= $block->escapeHtml(__('Zip/Postal Code')) ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="postcode"
                       value="<?= $escaper->escapeHtmlAttr($block->getFormData()->getPostcode()) ?>"
                       title="<?= $escaper->escapeHtmlAttr(__('Zip/Postal Code')) ?>"
                       id="zip_add"
                       class="input-text validate-zip-international <?= $escaper->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode')) ?>">
            </div>
        </div>
        <div class="field country required">
            <label class="label" for="country"><span><?= $block->escapeHtml(__('Country')) ?></span></label>
            <div class="control">
                <?= $block->getCountryHtmlSelect('country_id_add','country_id_add','country_add') ?>
            </div>
        </div> 
		<div> <input type="checkbox" checked="checked" id="save_in_add_book" name="save_in_add_book"/>Save in address book</div>
		 <div class="actions-toolbar">
        <div class="primary">
            <button type="submit"
					id="btn_save_quote_add"
                    class="action save primary"
                    data-action="save-address"
                    title="<?= $escaper->escapeHtmlAttr(__('Save Address')) ?>">
                <span><?= $block->escapeHtml(__('Save Address')) ?></span>
            </button>
        </div>
       
    </div>
    </fieldset>
   
</form>
	</div>
<script type="text/x-magento-init">
    {      
        "#country_add": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id_add",
                "regionInputId": "#region_add",
                "postcodeId": "#zip_add",
                "form": "#form-validate-quote-add-popup",
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= (int) $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<?php if(version_compare($version, '2.2.0', '>=')):?>

<script type="text/x-magento-init">
{
 "#form-validate-quote-add-popup": {
            "addressValidation": {}
        }
		}
</script>
<?php endif;?>
<script>
require(['jquery','Magento_Ui/js/modal/modal','mage/mage'],
function($, modal) {
var options = {
type: 'popup',
responsive: true,
innerScroll: true,
modalClass: 'custom-block-customer-address',
buttons: false,
};

	
$('#add_quote_bill_add,#add_quote_ship_add').click(function(){
	
	var button_id=$(this).attr('id');
	$('#quote_add_type').val(button_id);
var popup = modal(options, $('#popup-modal-address'));
$('#popup-modal-address').modal('openModal');
	$('#form-validate-quote-add-popup').trigger("reset");
	var action = $('#quoteItemlist').attr('action');
				action = action.replace("quotation/quote/updatePost", "quotation/customer/saveAddress");
					
					$('.form-address-edit').attr('action',action);
	
});
	
	
	});
</script>