<?php
namespace Magebees\QuotationManagerPro\Model\Quote;

class Status 
{
    
    const STARTING = 10;
    const STARTING_ACTION_STORE_OWNER = 11;
	const STARTING_ACTION_CUSTOMER = 12;
	const PROCESSING = 20;
    const PROCESSING_ACTION_STORE_OWNER = 21;
	const PROCESSING_ACTION_CUSTOMER = 22;
	const PROPOSAL_CREATED = 30;
	const PROPOSAL_SENT = 40;
	const PROPOSAL_SENT_ACTION_STORE_OWNER = 41;
	const PROPOSAL_SENT_ACTION_CUSTOMER = 42;
	const PROPOSAL_CANCELLED = 50;
	const PROPOSAL_CANCELLED_OUTOF_STOCK = 51;
	const PROPOSAL_REJECTED = 60;
	const PROPOSAL_ACCEPTED = 70;
	const PROPOSAL_ACCEPTED_NOT_ORDERED = 71;
	const PROPOSAL_ORDERED = 80;
	const PROPOSAL_PRINTED = 90;
	//const PROPOSAL_EXPIRED = 91;
	
		public function getOptionArray()
    {
		 $optionArray = array(
			self::STARTING =>__('NEW REQUESTED'),
			self::STARTING_ACTION_STORE_OWNER =>__('NEW REQUESTED ACTION FOR STORE OWNER'),
			self::STARTING_ACTION_CUSTOMER =>__('NEW REQUESTED ACTION FOR CUSTOMER'),
			self::PROCESSING =>__('PROPOSAL PROCESSING'),
            self::PROCESSING_ACTION_STORE_OWNER =>__('PROPOSAL PROCESSING ACTION STORE OWNER'),
			self::PROCESSING_ACTION_CUSTOMER =>__('PROPOSAL PROCESSING ACTION CUSTOMER'),
			self::PROPOSAL_CREATED =>__('PROPOSAL CREATED'),
			self::PROPOSAL_SENT =>__('PROPOSAL SENT'),
			self::PROPOSAL_SENT_ACTION_STORE_OWNER =>__('PROPOSAL SENT ACTION STORE OWNER'),
			self::PROPOSAL_SENT_ACTION_CUSTOMER =>__('PROPOSAL SENT ACTION CUSTOMER'),
			self::PROPOSAL_CANCELLED =>__('PROPOSAL CANCELLED'),
			self::PROPOSAL_CANCELLED_OUTOF_STOCK =>__('PROPOSAL CANCELLED OUTOF STOCK'),
			self::PROPOSAL_REJECTED =>__('PROPOSAL REJECTED'),
			self::PROPOSAL_ACCEPTED =>__('PROPOSAL ACCEPTED'),
			self::PROPOSAL_ORDERED =>__('PROPOSAL ORDERED')
			//self::PROPOSAL_EXPIRED =>__('QUOTE PROPOSAL EXPIRED')
        );
		return $optionArray;
	}
   
}
