<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block footer-columns">
    <div class="cols">
        <div class="col col-6">
            <?= $block->getChildHtml('footer_column_1') ?>
        </div>
        <div class="col col-6">
            <?= $block->getChildHtml('footer_column_2') ?>
        </div>
    </div>
</div>
